[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "write", path = "./reports" }]
ffi = true
optimizer = true
optimizer_runs = 200
solc = '0.8.27'
evm_version = 'shanghai'
bytecode_hash = 'none'

[profile.linea]
evm_version = 'london'

[profile.zksync]
src = 'zksync'
test = 'zksync'
libs = ['lib']
solc = '0.8.27'
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "write", path = "./reports" }]
ffi = true
evm_version = 'cancun'

[profile.zksync.zksync]
bytecode_hash = 'none'
compile = true
fallback_oz = true
mode = '3'
zksolc = '1.5.13'

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
polygon = "${RPC_POLYGON}"
polygon_amoy = "${RPC_POLYGON_AMOY}"
avalanche = "${RPC_AVALANCHE}"
avalanche_fuji = "${RPC_AVALANCHE_FUJI}"
arbitrum = "${RPC_ARBITRUM}"
arbitrum_sepolia = "${RPC_ARBITRUM_SEPOLIA}"
fantom = "${RPC_FANTOM}"
fantom_testnet = "${RPC_FANTOM_TESTNET}"
optimism = "${RPC_OPTIMISM}"
optimism_sepolia = "${RPC_OPTIMISM_SEPOLIA}"
harmony = "${RPC_HARMONY}"
sepolia = "${RPC_SEPOLIA}"
scroll = "${RPC_SCROLL}"
scroll_sepolia = "${RPC_SCROLL_SEPOLIA}"
metis = "${RPC_METIS}"
base = "${RPC_BASE}"
base_sepolia = "${RPC_BASE_SEPOLIA}"
bnb = "${RPC_BNB}"
gnosis = "${RPC_GNOSIS}"
zkEVM = "${RPC_ZKEVM}"
celo = "${RPC_CELO}"
zksync = "${RPC_ZKSYNC}"
linea = "${RPC_LINEA}"
sonic = "${RPC_SONIC}"

[fmt]
tab_width = 2
