name: Test

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Foundry setup
        uses: bgd-labs/github-workflows/.github/actions/foundry-setup@main

      - name: Enforce linting
        run: forge fmt --check

  test-sol:
    name: Foundry build n test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: bgd-labs/action-rpc-env@main
        with:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

      # we simply use foundry zk for all jobs in this repo
      - name: Run Foundry setup
        uses: bgd-labs/github-workflows/.github/actions/foundry-setup@main

      - name: Run Forge tests
        id: test
        uses: bgd-labs/github-workflows/.github/actions/foundry-test@main

      - name: Run Gas report
        uses: bgd-labs/github-workflows/.github/actions/foundry-gas-report@main

      - name: Run Lcov report
        uses: bgd-labs/github-workflows/.github/actions/foundry-lcov-report@main

      - name: Store artifact
        uses: bgd-labs/github-workflows/.github/actions/comment-artifact@main

      # we let failing tests pass so we can log them in the comment, still we want the ci to fail
      - name: Post test
        if: ${{ steps.test.outputs.testStatus != 0 || steps.zktest.outputs.testStatus != 0 }}
        run: |
          echo "tests failed"
          exit 1
